---
title: "About Quin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**QUIN SMITH** hails from San Diego, CA and is a 2022 graduate of the Bren School of Environmental Science & Management at UC Santa Barbara. He currently holds a Master of Environmental Science and Management. In 2013, he received his Bachleor of Arts degree in Film and Electronic Arts from Cal State University, Long Beach. 

Before entering the environmental science field, Quin worked in the entertainment industry as a freelance production assistant, a courier for Warner Brothers Studios, and a production artist at a graphic design agency for movies and TV.  After a career pivot in 2016, Quin returned to school to focus on STEM coursework. He obtained field and research experience by volunteering in conservation efforts including native wetland habitat restoration with the [San Elijo Lagoon Conservancy](https://thenaturecollective.org/), fishery health assessment with the California Department of Fish and Wildlife, and conservation work with critically endangered white abalone at the [NOAA Southwest Fisheries Science Center](https://www.fisheries.noaa.gov/about/southwest-fisheries-science-center) in La Jolla.  

For two field seasons, Quin was employed by [University of California](http://cesandiego.ucanr.edu/) studying the attractiveness of common ornamental plants to insect pollinators.  In September of 2019, he began employment with [UCSB’s San Onofre Nuclear Generating Station Mitigation Monitoring Program](https://marinemitigation.msi.ucsb.edu/) as a wetlands field and lab assistant.  This work provided foundational experience in remote sensing and image classification, experimental design, and field collection.  

Quin received an Associate of Science degree in Geographic Information Systems from Palomar College in 2020.  As a Bren MESM graduate with a Conservation Planning specialization, Quin is interested in the application of GIS and remote sensing in wetlands ecology and is broadly interested in putting drone and LiDAR technology to the test in environmental research and analysis.






